# 로컬 개발 환경에서의 설정
spring:
  config:
    name: application-dev
    activate:
      on-profile: dev
    location: classpath:/application-dev.yml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3306/nestnet?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ${mysql-pw}

  data:
    redis:
      host: host.docker.internal
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true                                    # sout으로 보기에 편안한 sql 출력
        dialect: org.hibernate.dialect.MySQL8Dialect        # mysql 방언
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug    # 하이버네이트가 생성하는 sql 로그로 출력
    org.hibernate.orm.jdbc.bind: debug    # 쿼리 파라미터 로그 남김
    root: debug

filePath: C:\nestnetFile\


